# Generated by Django 3.0.3 on 2020-12-20 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic_list', '0004_auto_20201220_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basiclist',
            name='owner',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='basic_list', to=settings.AUTH_USER_MODEL),
        ),
    ]
