# Generated by Django 3.0.3 on 2020-12-22 05:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('basic_list', '0006_auto_20201220_1131'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='basicList',
            new_name='todoList',
        ),
    ]
