# Generated by Django 3.0.3 on 2020-12-19 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='avatar',
            field=models.ImageField(default='default.jpg', upload_to='upload_pics'),
        ),
    ]
