# Generated by Django 3.0.3 on 2020-12-05 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='basicList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(default='default.jpg', upload_to='upload_pics')),
                ('title', models.CharField(max_length=100)),
                ('href', models.CharField(max_length=100)),
                ('subDescription', models.CharField(max_length=100)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
