# Generated by Django 3.0.3 on 2020-12-09 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_basiclist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='author',
        ),
        migrations.RemoveField(
            model_name='article',
            name='date',
        ),
        migrations.RemoveField(
            model_name='article',
            name='email',
        ),
    ]
